// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClMOvQacQU_JJqB_z-1WvONBBS3KB5KAM',
    appId: '1:818483951559:ios:d797a9cb1e4ded49cf4be2',
    messagingSenderId: '818483951559',
    projectId: 'safe-city-f5356',
    storageBucket: 'safe-city-f5356.firebasestorage.app',
    iosBundleId: 'com.example.safeCity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8bX8rpygIK7MIna7ovzXwf9jcHjmMgRk',
    appId: '1:818483951559:web:d8a246171d3d51cacf4be2',
    messagingSenderId: '818483951559',
    projectId: 'safe-city-f5356',
    authDomain: 'safe-city-f5356.firebaseapp.com',
    storageBucket: 'safe-city-f5356.firebasestorage.app',
    measurementId: 'G-4JR56Y1M5S',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8bX8rpygIK7MIna7ovzXwf9jcHjmMgRk',
    appId: '1:818483951559:web:d8a246171d3d51cacf4be2',
    messagingSenderId: '818483951559',
    projectId: 'safe-city-f5356',
    authDomain: 'safe-city-f5356.firebaseapp.com',
    storageBucket: 'safe-city-f5356.firebasestorage.app',
    measurementId: 'G-4JR56Y1M5S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClMOvQacQU_JJqB_z-1WvONBBS3KB5KAM',
    appId: '1:818483951559:ios:d797a9cb1e4ded49cf4be2',
    messagingSenderId: '818483951559',
    projectId: 'safe-city-f5356',
    storageBucket: 'safe-city-f5356.firebasestorage.app',
    iosBundleId: 'com.example.safeCity',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyEA4gKvQUmVFfIYO6RbYuyPe3LA0-Peo',
    appId: '1:818483951559:android:4ecf94e35986d28ccf4be2',
    messagingSenderId: '818483951559',
    projectId: 'safe-city-f5356',
    storageBucket: 'safe-city-f5356.firebasestorage.app',
  );

}